# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Страница имени Александра Кулдыкина
meta_description: Моё имя Александр Кулдыкин и я разработчик работующий с Java и JavaScript.
description: Моё имя <span itemprop='author' itemscope itemtype='https://schema.org/Person'>Александр Кулдыкин</span> и я разработчик работующий с Java и JavaScript. Мой Twitter <a href='https://twitter.com/kuldikin' alt='@kuldikin on Twitter' title='@kuldikin on Twitter'>@kuldikin</a>.
author: Александр Кулдыкин
email: kuldikin@gmail.com
pubkey:
twitter: kuldikin
language: ru
timezone: Europe/Moscow

# Menu
menu:
  Главная: '/'
  Публикации: '/articles'
  Об авторе: '/about'

# Disqus
disqus_shortname: kuldikincom

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kuldikin.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - drafts/**

# Archives
archive_generator:
  per_page: 0
  yearly: true
  monthly: false
  daily: false

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: dddd Do MMM YYYY
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: flexy
exclude_generator: ['tag', 'category']

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/
markdown:
  render:
    html: true # escape HTML content
    xhtmlOut: false # produce fully XHTML compliant code
    breaks: false # don't produce `<br>` on line break
    linkify: true # returns text links as HTML links
    typographer: true # substitute common elements like (c)
  anchors:
    level: 2
    permalink: false
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub

# Stylus
## https://github.com/hexojs/hexo-renderer-stylus
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

# Autoprefixer
## https://github.com/hexojs/hexo-autoprefixer
autoprefixer:
  enable: true
  debug: true
  cascade: false
  browsers:
    - '> 5%'
    - 'last 2 versions'
  safe: false
  exclude:
    - '*.min.js'

# BrowserSync
## https://www.browsersync.io/docs/options/
browsersync:
  logSnippet: false
  logLevel: "info" # info, debug, silent
  logConnections: true
  logFileChanges: true
  reloadOnRestart: true
  injectChanges: true

# CleanCSS
## https://github.com/hexojs/hexo-clean-css
clean_css:
  compatibility: true
  processImport: true
  exclude:
    - '*.min.css'

# HTMLMinifier
## https://github.com/hexojs/hexo-html-minifier
# html_minifier:
#   collapseWhitespace: true
#   exclude:
#   removeComments: true
#   useShortDoctype: true
#   minifyJS: true

# Uglify
## https://github.com/hexojs/hexo-uglify
uglify:
  mangle: true # single letter vars
  output:
  compress:
  comments: # `all` to keep
  exclude:
    - '*.min.js'

# RSS Feed
## https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: /atom.xml
  limit: 50
  content: true

# Sitemap
## https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: /sitemap.xml

# Server
## https://github.com/hexojs/hexo-server
server:
  port: 4000
  log: false
  ip: 0.0.0.0

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:kuldikin/kuldikin.github.io.git
  branch: master
